name: "Build Cross-Platform"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          
      - name: Install dependencies
        run: npm install
        
      - name: Build Tauri App
        run: npm run tauri build
        
      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-app
          path: src-tauri/target/release/bundle/nsis/*.exe
          retention-days: 3

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          
      - name: Install dependencies
        run: npm install
        
      - name: Build Tauri App
        run: npm run tauri build
        
      - name: Upload MacOS artifacts
        uses: actions/upload-artifact@v3
        with:
          name: macos-app
          path: |
            src-tauri/target/release/bundle/dmg/*.dmg
            src-tauri/target/release/bundle/macos/*.app
          retention-days: 3
